### ISSUE TITLE
please consider changing the name

### ISSUE THREAD

**Issue by gabor** [Dean177/reason-standard#3]
hi,

could you consider changing the name of the project? the reason is that a name like "standard" sounds like something "official", something that should be used by default, etc, and for now i don't think it is correct. so to avoid confusion, some other name would be better.

something similar happened in javascript with the "javascript standard style" (https://standardjs.com/) which is in no way the standard for javascript.

**Comment by Dean177** [comment]
I will, a couple of people have made this point now.

Any suggestions?

**Comment by dylanirlbeck** [comment]
@Dean177 some suggestions https://github.com/reasonml/ideas-for-project-names-starting-with-re.

Alternatively, we could stay with the theme of commonly-used house items (inspired by`Tablecloth`) and do something like `Tablesheet`, `Bookshelf`, or `Backpack`. These are a bit silly but it's just a few ideas 😃

**Comment by idkjs** [comment]
reason-tablecloth, tablecloth-re, tablecloth-plus, nappe(tablecloth in french), tabili(yoruba)

**Comment by osener** [comment]
Replete

**Comment by stfnsr** [comment]
How about
`recalibrate` (as it got 'lib' in it, and sounds like something that is tuned and precise),
`reassure` (as safety is mentioned on the homepage)
`realign` (bc you mention having the same api for ocaml and bucklescript)

ditching the 're' prefix however my clear favorite would be:

`placemat`
This acknowledges the connection with tablecloth while still being different, and might sound humble (because of the size of a placemat).
Also, a placemat provides a uniform surface for the stuff you do on top of it, without obscuring what is underneath :)

**Comment by stfnsr** [comment]
If interested in some degree of continuity with the current name,
`outstand` for emphasizing quality,
`kickstand` for offering stability without holding you back
or `hardstand` - a surface on which you can place even the heaviest stuff, would come to mind.

That said, i'm still firmly on team `placemat` :D

**Comment by RicheyRyan** [comment]
I'd like to also give my support for a name change as I think it will help a lot with searchability. I quite like Bedrock and Backpack as names.

**Comment by rafaelfesi** [comment]
> I'd like to also give my support for a name change as I think it will help a lot with searchability.

I agree with that! The name "standard" is not good for searchability in search engines.

**Comment by rafaelfesi** [comment]
> `placemat` ⬜

IMO this seems to be the best name for the project so far.

**Comment by Dean177** [comment]
Good news, I spoke with @pbiggar today and we have decided to join forces on Tablecloth.

We still need to sketch out the exact shape of the resulting libraries, but we will definitely be sticking with `Tablecloth` as a name.

**Comment by micahscopes** [comment]
I was gonna say you could have called it "underwear" that'd be a good name for a standard library but oh well it's too late
