### ISSUE TITLE
Consider using FROM instead of OF for conversions

### ISSUE THREAD

**Issue by danielo515** [Dean177/reason-standard#4]
Hello.
Reading the docs I was excited about the human readable first thing. That's why I am surprised to see `book.ofInt` rather than `Bool.fromInt`. Isn't the latter easier to read and understand ? What is the motivation? 
Maybe you can just provide aliases ?

**Comment by Dean177** [comment]
Thanks for opening the issue danielo515. 

My reasoning was:
- ofX is already a convention in OCaml's standard library (Float.of_int)
- `of` is shorter than `from`

I would rather provide a single function than creating aliases.

I'm not super attached to `of` though, and could be convinced `from` is the way to go.

**Comment by danielo515** [comment]
Well, I can't argue against a language idioms. It is just that from feels more human and less academic. Probably it has something to do with the fact that English is not my main language.
Thank your for providing your reasoning. 
If nobody else wants to say anything you can close the issue whenever you consider

**Comment by Dean177** [comment]
@danielo515 we are going to merge the repository with https://github.com/darklang/tablecloth, and in doing so, adopt the `fromType` / `toType` convention. @sarna did you disagree with this?

**Comment by sarna** [comment]
@Dean177 I just like the foo_of_bar idiom more, is all :)

**Comment by danielo515** [comment]
> @danielo515 we are going to merge the repository with https://github.com/darklang/tablecloth, and in doing so, adopt the `fromType` / `toType` convention. @sarna did you disagree with this?

Awesome!

**Comment by Dean177** [comment]
Yes

**Comment by Dean177** [comment]
Over the next couple of weeks the extra functionality will be ported over
