### ISSUE TITLE
Deprecated special raw forms for functions

### ISSUE THREAD

**Issue by sarna** [Dean177/reason-standard#6]
Hello,

Love the library! Finally found an stdlib replacement with good docs :)

The only problem is, I can't build it - I'm getting a lot of deprecation warnings and they're configured as errors for some reason (I'm new to BuckleScript, sorry).

They should be pretty straightforward to fix, an example warning looks like this:
``` 
Warning number 22 (configured as error) 
  /home/me/code/typer/node_modules/reason-standard/bucklescript/src/Standard.ml 702:18-20
  
  700 ┆ let remainder (n : t) ~(by : t) = (modulo n ~by : t)
  701 ┆ 
  702 ┆ let power = ([%raw fun a b -> "{return a ** b}"] : t -> t -> t)
  703 ┆ 
  704 ┆ let ( ** ) (base : t) (exponent : int) : t = power base (ofInt exponent)
  
  Special raw form for function is deprecated, plain [%raw ".."] is recommended
```

**Comment by Dean177** [comment]
Is this a project using standard or building standard itself?

**Comment by sarna** [comment]
I tried adding Standard to my Reason/BuckleScript project, following the guidelines here: https://reason-standard.netlify.app/docs/installation

**Comment by Dean177** [comment]
Short term you can disable the warning: https://bucklescript.github.io/docs/en/build-configuration#warnings 

I am a little busy with family stuff at the moment, so it might be a while for me to do a new release.

A PR would be amazing though, this is the relevant section in the Bucklescript docs: https://bucklescript.github.io/docs/en/embed-raw-javascript#docsNav

**Comment by sarna** [comment]
No worries, family comes first :)

I’ll try to prepare a PR this week.
